[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer_runs = 9999999
via_ir = true
cache_path = "build/cache"
fs_permissions = [
    { access = "read", path = "./"},
    { access = "write", path = "./deployments" }
]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# Compiler Settings
solc = '0.8.28'                # Solidity compiler version
optimizer = true               # Enable optimizer