# Project Structure
[profile.default]
src = "src"                     # Source directory
out = "out"                     # Output directory for compiled contracts
libs = ["lib"]                  # Libraries directory
cache_path = "build/cache"      # Cache directory for builds

# Compiler Settings
solc = '0.8.28'                 # Solidity compiler version
optimizer = true                # Enable optimizer
optimizer_runs = 200            # Target number of contract runs for optimizer
via_ir = true                   # Compile through IR for additional optimizations

# Output Settings
ast = true                       # Output AST (Abstract Syntax Tree)
build_info = true                # Include build info in output
extra_output = ["storageLayout"] # Additional output formats

# Security & Permissions
fs_permissions = [
    { access = "read", path = "./" },            # Read access to project directory
    { access = "write", path = "./deployments" } # Write access to deployments directory
]
ffi = true                      # Allow foreign function interface (for system commands)

# Network Configuration
[rpc_endpoints]
anvil = "http://localhost:8545"              # Local development network
sepolia = "${SEPOLIA_RPC_URL}"               # Sepolia testnet (from environment variable)

# Block Explorer API Keys
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }   # Etherscan API key for Sepolia verification

# For more configuration options, visit:
# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options